### ISSUE TITLE
Facet stats failing to unmarshal for float type of fields

### ISSUE THREAD

**Issue by adilansari** [typesense/typesense-api-spec#27]
## Description

[FacetCounts.stats](https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml#L2001-L2014) is failing to unmarshal. It appears that they may be wrongly typed. For ex - `max` is typed as integer in API but actually could return a float value internally.

A couple examples in code:
- https://github.com/typesense/typesense/blob/8c2b1f3dfb61817d74b0cefa40cd69a796680394/include/field.h#L534-L539
- https://github.com/typesense/typesense/blob/483ed4d533e8a657784472e3a3066298fa085c44/src/index.cpp#L1051-L1061

## Steps to reproduce
- Have a collection with float/double numeric fields
- Send a facet query on these fields

## Expected Behavior
- Openapi should be defined as:
```
        stats:
          type: object
          properties:
            max:
              type: number
              format: float
            min:
              type: number
              format: float
            sum:
              type: number
              format: float
            total_values:
              type: integer
            avg:
              type: number
              format: float
```

## Actual Behavior
![image](https://user-images.githubusercontent.com/2469198/178569161-5e3da134-ed10-4305-8670-6d080c8cf5fe.png)
Document contains float fields

## Metadata

**Typsense Version**: 0.23.0

**OS**: MacOS
